### ISSUE TITLE
Portal context is not passed to child components

### ISSUE THREAD

**Issue by arusanov** [developit/preact-portal#1]
Context of parent component isn't passed to children in

```
renderLayer(show=true) {
		....
		this.remote = render((
			<PortalProxy>{ show && this.props.children || null }</PortalProxy>
		), this.into, this.remote);
	}
```

For example if we have some context at the root (redux store) it won't be passed to children of `<Portal>`
http://jsfiddle.net/4tLucu6h/1/

**Comment by developit** [comment]
@arusanov Fixed and released as [1.1.0](https://github.com/developit/preact-portal/releases/tag/1.1.0)
