### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by garkin** [developit/preact-portal#3]
This doesn't look compatible with [preact-render-to-string](https://github.com/developit/preact-render-to-string).

**Comment by developit** [comment]
Indeed! I'm not sure it's be possible to make it compatible since that renderer is synchronous and top down. This library works with preact's default DOM renderer inside of jsdom or [undom](https://github.com/developit/undom) though. Might be a good option for you!

**Comment by garkin** [comment]
I am concerned about overhead of taking additional DOM imitations inside server rendering. 
Whole point of using React like solution was to have a seamless server side rendering.

Currently in case of server rendering i hook modified `Portal.render` with a handler passed through context, and then manually get another `renderToString` pass for hooked modal subtree.

Only more idiomatic solution i could think about is to have a `<PortalTarget>` inside `<App>` and then make it communicate with `<Portal>`'s through registry inside of context. 
To create such registry it will need another `<PortalContext>` around `<App>`. 
It looks like due synchronous nature of `renderToString` (and may be even `Preact.render`) there will be a limitation to have `<PortalProxy>` always have to be after relevant instances of `<Portal>`.
Which all together don't look like an elegant option anymore.

**Comment by developit** [comment]
Thought: what about having your PortalTarget output a placeholder and then aggregating Portal outputs for injection by placeholder after render?

**Comment by garkin** [comment]
Would be really cool to see such comparison.
